config/routes.rb
Rails.application.routes.draw do
  #home
  root to: "welcome#index"
  #auth
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  #users
  get "/sign_up", to: "users#new", as: "sign_up"
  resources :users
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts, dependent: :destroy

  def self.confirm(email_param, password_param)
    user = User.find_by({email: email_param})
    user.authenticate(password_param)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def json_auth
    unless current_user
      render json: {
        error: "you do not have privileges to view this content"
      }
    end
  end

  helper_method :current_user #make it available in views
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #pass in array that user_params returns as arguments using a splat
    user = User.confirm(params[:email], params[:password])
    if user
      #this creates the session, logging in the user
      session[:user_id] = user.id
      #redirect to the show page
      redirect_to user_path(user.id)
    else
      #there was an error logging the user in
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :json_auth, only: :index

  def index
    #caches posts
    users = User.includes(:posts)
    # packages posts into a users json object, excluding certain attributes
    render json: users.as_json(include: :posts, except: [:password_digest, :updated_at])
  end

  def new
    @user = User.new
    render :new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      #login user
      session[:user_id] = @user.id
      #redirect to user#show
      redirect_to @user
    else
      #there was an error, go back to signup page
      #TODO: pack errors into a flash message & pass to :new view 
      render :new
    end
  end

  def show
    @user = current_user
  end

  def destroy
    #find & destroy user
    #redirect home
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.find_by_id(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user do |f| %>
  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.label :password %>:
  <%= f.password_field :password %><br />

  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Hello <%=@user.email%></p>

app/views/welcome/index.html.erb
<% if current_user %>

<h1>Welcome <%= @user.email %> </h1>

<%= link_to "Profile", user_path(current_user), method: :get %>

<%= link_to "Logout", sessions_path, method: :delete %> 

<% else %>

<h1>Welcome</h1>

<%= link_to "Signup", sign_up_path, method: :get %>

<span>or</span>

<%= link_to "Login", login_path, method: :get %>

<% end %>